---
abstract: 'Determine file type'
author:
  - 'Jaap Karssenberg <pardus@cpan.org>'
build_requires: {}
configure_requires:
  Module::Build: 0.40
dynamic_config: 1
generated_by: 'Module::Build version 0.4005, CPAN::Meta::Converter version 2.132140'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: File-MimeInfo
provides:
  File::MimeInfo:
    file: lib/File/MimeInfo.pm
    version: 0.18
  File::MimeInfo::Applications:
    file: lib/File/MimeInfo/Applications.pm
    version: 0.18
  File::MimeInfo::Magic:
    file: lib/File/MimeInfo/Magic.pm
    version: 0.18
  File::MimeInfo::Rox:
    file: lib/File/MimeInfo/Rox.pm
    version: 0.18
requires:
  Carp: 0
  Exporter: 0
  Fcntl: 0
  File::BaseDir: 0.03
  File::DesktopEntry: 0.04
  Pod::Usage: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.18
