---
abstract: 'Determine file types'
author:
  - 'Jaap Karssenberg <pardus@cpan.org>'
build_requires:
  Carp: 0
  Exporter: 0
  Fcntl: 0
  File::BaseDir: 0.03
  File::DesktopEntry: 0.04
  Pod::Usage: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.8, CPAN::Meta::Converter version 2.132830'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: File-MimeInfo
no_index:
  directory:
    - t
    - inc
requires:
  perl: 5.006001
resources:
  bugtracker: https://github.com/mbeijen/File-MimeInfo/issues
  repository: https://github.com/mbeijen/File-MimeInfo
version: 0.25
